### ISSUE TITLE
Increase the width of categories badge in list view

### ISSUE THREAD

**Issue by itsmohmans** [Marje3PSUT/psutarchive#44]
![image](https://github.com/Marje3PSUT/psutarchive/assets/55551984/6c50bfda-8777-4587-b268-061334891118)

Currently, it only shows the first categories, and the rest are clipped. It should have more width.

**Comment by lusifer65** [comment]
hi @itsmohmans 
can you please tell me the step to reproduce this bug

**Comment by mohtasheem135** [comment]
Hello bro, can you please assign this to me....I can do this

**Comment by Virtual4087** [comment]
I'd like to work on this. I'm familiar with vue
